/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HoverlaSoftLiBannersRouteImport } from './routes/hoverla-soft/li-banners'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoverlaSoftLiBannersRoute = HoverlaSoftLiBannersRouteImport.update({
  id: '/hoverla-soft/li-banners',
  path: '/hoverla-soft/li-banners',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hoverla-soft/li-banners': typeof HoverlaSoftLiBannersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hoverla-soft/li-banners': typeof HoverlaSoftLiBannersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hoverla-soft/li-banners': typeof HoverlaSoftLiBannersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hoverla-soft/li-banners'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hoverla-soft/li-banners'
  id: '__root__' | '/' | '/hoverla-soft/li-banners'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HoverlaSoftLiBannersRoute: typeof HoverlaSoftLiBannersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoverla-soft/li-banners': {
      id: '/hoverla-soft/li-banners'
      path: '/hoverla-soft/li-banners'
      fullPath: '/hoverla-soft/li-banners'
      preLoaderRoute: typeof HoverlaSoftLiBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HoverlaSoftLiBannersRoute: HoverlaSoftLiBannersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
